# Generated by Django 5.0.1 on 2024-02-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_categoriy_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
