# Generated by Django 5.0.1 on 2024-02-29 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_author'),
        ('users', '0003_alter_author_options_alter_author_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorlike',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.product'),
            preserve_default=False,
        ),
    ]
