# Generated by Django 5.0.1 on 2024-02-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authorlike_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorlike',
            name='product',
        ),
    ]
