# Generated by Django 5.0.1 on 2024-02-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_product_authorcardmarket_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorcardmarket',
            old_name='authorS',
            new_name='authors',
        ),
    ]
